### ISSUE TITLE
License for the code

### ISSUE THREAD

**Issue by erangac** [srid99/protostuff-example#1]
Hi,

Under which license, are you distributing this code ? I am interesting to reuse few of your classes.

Thanks

**Comment by srid99** [comment]
Hey, Good to know that you like to reuse few things. I added [Apache License](http://www.apache.org/licenses/LICENSE-2.0) for the project. Feel free to use them (some points to be aware of that this project is an year old and done real quick)

**Comment by erangac** [comment]
Thanks Sirdhar.  I only use few classes related to protostuff.

**Comment by srid99** [comment]
No problem. Have fun!
